name: Check
on:
  push
jobs:
  scalafmt:
    runs-on: "eed3si9n/sbt:jdk11-alpine"
    steps:
      - name: check scalafmtAll
        run: sbt scalafmtCheckAll
      - name: check scalafmtSbt
        run: sbt scalafmtSbtCheck
